### ISSUE TITLE
works with NATS Streaming ?

### ISSUE THREAD

**Issue by joeblew99** [nats-io/nats-rest-config-proxy#16]
THis is really useful because then users can make the scripts and they become part of the provisioning / migration scripts.

But i am not sure this works with NATS Streaming ?

**Comment by ColinSullivan1** [comment]
Good to hear it's useful!  However, it does not work with NATS streaming at the moment, only the core NATS server (`nats-server`).

**Comment by wallyqs** [comment]
We can't support STAN as is because of the subjects being dynamic, but we started to add support jetstream so will close this one for now.
