### ISSUE TITLE
Already exists in different account error

### ISSUE THREAD

**Issue by MatasMarko** [nats-io/nats-rest-config-proxy#42]
Hello,

I have a python script running that generates a config using your nats-rest-config-proxy. Creating accounts, snapshots and publishing - works, but as soon as it creates a second account I receive this error:

```
[ERR] Error:  already exists in different account
```

The full output with config tree : 

```
matas@matas ~/ssd/nats/config ❯ tree
.
├── current
│   └── accounts
│       ├── Dev.json
│       └── auth.conf
├── resources
│   ├── accounts
│   │   ├── Dev.json
│   │   ├── Google.json
│   │   └── Yahoo.json
│   ├── permissions
│   │   └── admin.json
│   └── users
│       ├── Firm11.json
│       └── server.json
└── snapshots

7 directories, 8 files
matas@matas ~/ssd/nats/config ❯ [1934883] 2020/10/28 13:46:53.369960 [INF] Updating user resource "Firm111"
[1934883] 2020/10/28 13:46:53.370105 [ERR] Error:  already exists in different account
[1934883] 2020/10/28 13:46:53.370123 [TRC] 127.0.0.1 - "PUT /v1/auth/idents/Firm111 HTTP/1.1" 112 409 0.000001
```

Tried publishing the configuration, then trying to add another user, also tried changing the name of the user, adding users from command line, but none of them worked.

Hope to hear from you soon.

Best Regards,
Matt

**Comment by wallyqs** [comment]
Hi @MatasMark , can I get a few examples of the payloads that you are sending to the proxy? Generally the `already exists in different account` error should mean that a username has to be unique across accounts.

**Comment by MatasMarko** [comment]
Thanks for the fast reply @wallyqs !

I had a further look on what was going on.

I am using NKeys public key for validation, therefore, there is no username or password in my case. 
Already exists error was thrown because there were two identical usernames which were the same empty string.   
The users file looks like this:

`{
  "nkey": "UAEATNZLX6IEAKORMR6S5ROU74KH34ZMOG5YZYRGEGZ4GBLV447MF7IV",
  "permissions": "admin",
  "account": "Google"
}
`
I have fiddled with handlers.go file and it seems to be working as intended now. I have created a Pull request #43 with the fixes that I have done. Please note that I am not a Go developer and the code could be optimized (or written better), so feel free to edit or rewrite.
Also, I hope that I did not misunderstood the usage of NKeys.

Thank you for your time!

**Comment by wallyqs** [comment]
Thank you @MatasMarko for sharing how to reproduce 👍  We will take a look and likely have a release next week with the fix.
